version: "3"

networks:
  infrastructure:
    external: false

services:
  postgres:
    image: postgres:${PGVERSION-9.5}-alpine
    volumes:
    - ./postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
    - ./.env
    environment:
      TZ: ${TZ-Australia/Melbourne}
    networks:
    - infrastructure
    command: ['postgres', '-c', 'dgit.principal=', '-c', 'dgit.tid=']

  testsql:
    # need an image with psql and either unzip or jar
    image: postgres:${PGVERSION_CLIENT:-10}-alpine
    volumes:
    - .:/app:ro
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${APP_POSTGRES_USER}
      PGPASSWORD: ${APP_POSTGRES_PASSWORD}
      PGUSER_SUPER: ${POSTGRES_USER}
      PGPASSWORD_SUPER: ${POSTGRES_PASSWORD}
      TEST_DB: ${APP_POSTGRES_DATABASE}
      GROW_TX_BREAKOUT_RESPONSE: exception
    networks:
    - infrastructure
    working_dir: /app
    command: ./testsql.sh
    user: nobody
#    stdin_open: true
#    tty: true
#    command: bash

  secore-template:
    environment:
      DS_URL: jdbc:postgresql://postgres:5432/${APP_POSTGRES_DATABASE}
      DS_USERNAME: ${APP_POSTGRES_USER}
      DS_PASSWORD: ${APP_POSTGRES_PASSWORD}
      PGUSER_SUPER: ${POSTGRES_USER}
      PGPASSWORD_SUPER: ${POSTGRES_PASSWORD}
      GROW: ${GROW-upgrade}
